### ISSUE TITLE
Lodash dependency broken

### ISSUE THREAD

**Issue by vesakilp** [jquense/react-formal#88]
With formal version 0.20.2 I'm getting following error(0.20.1 works fine): 

`module.js:341
    throw err;
    ^

Error: Cannot find module 'lodash/has'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([app path]/node_modules/react-formal/lib/util/chainEvents.js:9:12)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] ([app path]/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)`

**Comment by maullerz** [comment]
@vesakilp 
Did you tried to update to 0.21.1 version?

**Comment by vesakilp** [comment]
Yeah, the problem was when using semver, we're not getting minor versions with careting because react-formal major version is zero. That's why we're not getting minor version bumps with careting and ended up using 0.20.2. https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004
